[package]
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Eirik Ogilvie-Wigley <eowigley@gmail.com>",
    "Jack Grigg <thestr4d@gmail.com>",
    "CPerezz <carlos@dusk.network>"
]
description = "Dusk's fork of the implementation of the Jubjub elliptic curve group"
homepage = "https://github.com/dusk-network/jubjub"
license = "MIT/Apache-2.0"
name = "dusk-jubjub"
repository = "https://github.com/dusk-network/jubjub"
version = "0.5.1"
keywords = ["cryptography", "jubjub", "zk-snarks", "ecc", "elliptic-curve"]
categories =["algorithms", "cryptography", "science"]
edition = "2018"
exclude = [".github/workflows/ci.yml", "github/workflows/rust.yml",
".gitignore", 
]

[dependencies]
dusk-bls12_381 = {git = "https://github.com/dusk-network/bls12_381", branch = "vlopes11/no-std-pairings", default-features = false}
blake2 = "0.9.0"
canonical = {version = "0.4", optional = true}
canonical_derive = {version = "0.4", optional = true}

[dependencies.subtle]
version = "^2.3"
default-features = false

[dev-dependencies.rand]
version = "0.7"

[dependencies.rand_core]
version = "0.6"
default-features = false

[dev-dependencies.rand_xorshift]
version = "0.2"
default-features = false

[features]
default = ["std"]
std = ["dusk-bls12_381/alloc"]
canon = ["canonical", "canonical_derive", "dusk-bls12_381/canon"]
